#!/bin/bash

echo "#############################################" >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "##### INICIO DO PROCESSO DE ATUALIZAÇÃO #####" >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "#############################################" >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "                                             " >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "SUDO APT UPDATE #############################" >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
sudo apt update >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "                                             " >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "APT LIST --UPGRADABLE #############################" >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
apt list --upgradable >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "                                             " >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "APT LIST --UPGRADABLE #############################" >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
sudo apt full-upgrade -y >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "#############################################" >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "                                             " >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "                                             " >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "                                             " >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)
echo "                                             " >> /home/robisonjoel/.logs/log_update_$(date +%d-%m-%y_%H:%M)